### ISSUE TITLE
.text() including HTML?

### ISSUE THREAD

**Issue by Sasstraliss** [lazytiger/gumbo-query#10]
Would it be possible to have .text() include the HTML inside a node as well as the text content?

For example:
```
std::string te = "<div><span>1</span>2</div>";
CDocument cdo;
cdo.parse(te);
// cdo.find("div").nodeAt(0).text() should be "<span>1</span>2" not "12"
```

**Comment by zenden2k** [comment]
Yes it would be nice to have `.html()` like in jquery

**Comment by lazytiger** [comment]
According to the implementation of gumbo_parser, a .html function like .text can't be implemented gracefully in gumbo_query. Instead, I have CNode::startPos and CNode:endPos provided, see example/main.cpp test_html for detail.

**Comment by zenden2k** [comment]
maybe you can generate html code manually like here
https://github.com/craigbarnes/lua-gumbo/blob/master/gumbo/dom/Element.lua#L260

**Comment by lazytiger** [comment]
Yes, serialize is another way, but more consuming I think. For small changes, replacement may be a good idea.
