### ISSUE TITLE
Building on linux

### ISSUE THREAD

**Issue by andrecbarros** [lazytiger/gumbo-query#15]
May you add to cmake/FindGumbo.cmake libgumbo.so or libgumbo.so.1 ? It will allow a successful build on linux.

Patch example:

--- cmake/FindGumbo.cmake.orig  2015-08-06 20:37:13.000000000 -0300
+++ cmake/FindGumbo.cmake       2015-08-08 05:46:41.021517785 -0300
@@ -23,7 +23,7 @@
 
 # Finally the library itself
 find_library(Gumbo_LIBRARY
-  NAMES libgumbo.dylib libgumbo.dll gumbo.dylib gumbo.dll
+  NAMES libgumbo.dylib libgumbo.dll gumbo.dylib gumbo.dll libgumbo.so
   PATHS ${Gumbo_PKGCONF_LIBRARY_DIRS}
 )

**Comment by lazytiger** [comment]
Thanks for the remind, fixed.
