### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TechnikEmpire** [lazytiger/gumbo-query#19]
Since this library is based heavily on the cascadia GO library, it's recommended to include the original Author's copyright notice in your license file. Example:

`Copyright (c) 2011 Andy Balholm. All rights reserved.  `
`Copyright (c) 2015 baimashi.com.  `

Presently, your license doesn't reflect that your work is derived from another copyrighted work. Not trying to be nitpicky, just a suggestion. :)

References:
https://github.com/andybalholm/cascadia/blob/master/LICENSE
http://programmers.stackexchange.com/a/22261/22018

**Comment by lazytiger** [comment]
Thanks for the suggestion, it's done.
