### ISSUE TITLE
Brew unable to install and unable to make

### ISSUE THREAD

**Issue by usagiryu** [lazytiger/gumbo-query#34]
I follow the instruction and tried to install through brew

Tuzis-MacBook:build tuzi$ brew install gumbo-paerser
Error: No available formula with the name "gumbo-paerser" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

Thanks for your help

**Comment by bakercp** [comment]
brew install gumbo-parser

Check your spelling?
