### ISSUE TITLE
.find("tag[attribute*='somethingwithasinglequote']")

### ISSUE THREAD

**Issue by Sasstraliss** [lazytiger/gumbo-query#9]
If I have a span with the id "that's", I can't seem to use .find() to get to it:

.find("span[id*='that's']") doesn't work (error)
.find("span[id*='that\'s']") doesn't work (error)

An unhandled exception of type 'System.StackOverflowException' occurred in Parser.cpp

std::string ret = message + " at:";
	for (unsigned int i = ds.size() - 1; i >= 0; i--)
	{
		ret.push_back(ds[i]);
	}

**Comment by lazytiger** [comment]
There is no escape sequence enabled for now, because I am not sure what character should be escaped. Maybe we can make a rule about this first.
